baseURL = 'http://example.org/'
languageCode = 'zh-cn'
title = 'Fresh in Computer'
theme = 'blowfish'


[frontmatter]
  date = ['date', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = [':git', 'lastmod', 'date']
  publishDate = ['publishDate', 'date']
