baseURL = 'https://guide.samuka007.xyz/'
languageCode = 'zh-cn'
title = 'SCUT Computer Clinic'
theme = 'blowfish'


[frontmatter]
  date = ['date', 'lastmod']
  expiryDate = ['expiryDate']
  lastmod = ['lastmod', ':git', 'date']
  publishDate = ['publishDate', 'date']
